[package]
name = "thegameboysp/bb"
version = "0.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["examples"]

[dependencies]
t = "osyrisrblx/t@3.0.0"
Signal = "sleitnick/signal@1.1.0"
Promise = "evaera/promise@4.0.0"
Rodux = "roblox/rodux@3.0.0"
Llama = "freddylist/llama@1.1.1"
Roact = "roblox/roact@1.4.2"
RoactRodux = "roblox/roact-rodux@0.3.0"
RoactHooks = "kampfkarren/roact-hooks@0.3.0"
RoactSpring = "chriscerie/roact-spring@1.1.6"
TestEZ = "roblox/testez@0.4.1"
Rewire = "sayhisam1/rewire@0.3.0"

[server-dependencies]
Cmdr = "evaera/cmdr@1.9.0"